---
title: "Expedia"
author: "Shane Huang"
date: "9/1/2020"
output: html_document
---

```{r}
# Libraries
library(tidyverse)

```

```{r}
train <- read_csv("train.csv")
test <- read_csv("test.csv")
```

```{r}
# Shane
```

```{r}
# McKay
# Eda
colnames(train)

unique(train$Response)

sum(is.na(train$Medical_History_10))/nrow(train)
sapply(train[,2:8], unique)

train %>% select(starts_with("Medical_History")) %>% sapply(unique)

```
```{r}
to.clean <- rbind(cbind(test, Response = NA),train)


#seeing which values are missing
missing.values <- to.clean %>%
  gather(key = "key", value = "val") %>%
  mutate(isna = is.na(val)) %>%
  group_by(key) %>%
  mutate(total = n()) %>%
  group_by(key, total, isna) %>%
  summarise(num.isna = n()) %>%
  mutate(pct = num.isna / total * 100)

levels <-
    (missing.values  %>% filter(isna == T) %>% arrange(desc(pct)))$key

percentage.plot <- missing.values %>%
      ggplot() +
        geom_bar(aes(x = reorder(key, desc(pct)), 
                     y = pct, fill=isna), 
                 stat = 'identity', alpha=0.8) +
      scale_x_discrete(limits = levels) +
      scale_fill_manual(name = "", 
                        values = c('steelblue', 'tomato3'), labels = c("Present", "Missing")) +
      coord_flip() +
      labs(title = "Percentage of missing values", x =
             'Variable', y = "% of missing values")

percentage.plot
```